[build]
builder = "dockerfile"
buildCommand = "echo 'Building with Dockerfile...'"

[deploy]
startCommand = "/start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/status"
healthcheckTimeout = 30

[env]
NODE_ENV = "production"
PORT = "3000" 